import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";

const messages = [
  // Claude Code-ish single-word list
  "Accomplishing...",
  "Actioning...",
  "Actualizing...",
  "Architecting...",
  "Baking...",
  "Beaming...",
  "Beboppin'...",
  "Befuddling...",
  "Billowing...",
  "Blanching...",
  "Bloviating...",
  "Boogieing...",
  "Boondoggling...",
  "Booping...",
  "Bootstrapping...",
  "Brewing...",
  "Bunning...",
  "Burrowing...",
  "Calculating...",
  "Canoodling...",
  "Caramelizing...",
  "Cascading...",
  "Catapulting...",
  "Cerebrating...",
  "Channeling...",
  "Channelling...",
  "Choreographing...",
  "Churning...",
  "Clauding...",
  "Coalescing...",
  "Cogitating...",
  "Combobulating...",
  "Composing...",
  "Computing...",
  "Concocting...",
  "Considering...",
  "Contemplating...",
  "Cooking...",
  "Crafting...",
  "Creating...",
  "Crunching...",
  "Crystallizing...",
  "Cultivating...",
  "Deciphering...",
  "Deliberating...",
  "Determining...",
  "Dilly-dallying...",
  "Discombobulating...",
  "Doing...",
  "Doodling...",
  "Drizzling...",
  "Ebbing...",
  "Effecting...",
  "Elucidating...",
  "Embellishing...",
  "Enchanting...",
  "Envisioning...",
  "Evaporating...",
  "Fermenting...",
  "Fiddle-faddling...",
  "Finagling...",
  "Flambéing...",
  "Flibbertigibbeting...",
  "Flowing...",
  "Flummoxing...",
  "Fluttering...",
  "Forging...",
  "Forming...",
  "Frolicking...",
  "Frosting...",
  "Gallivanting...",
  "Galloping...",
  "Garnishing...",
  "Generating...",
  "Gesticulating...",
  "Germinating...",
  "Gitifying...",
  "Grooving...",
  "Gusting...",
  "Harmonizing...",
  "Hashing...",
  "Hatching...",
  "Herding...",
  "Honking...",
  "Hullaballooing...",
  "Hyperspacing...",
  "Ideating...",
  "Imagining...",
  "Improvising...",
  "Incubating...",
  "Inferring...",
  "Infusing...",
  "Ionizing...",
  "Jitterbugging...",
  "Julienning...",
  "Kneading...",
  "Leavening...",
  "Levitating...",
  "Lollygagging...",
  "Manifesting...",
  "Marinating...",
  "Meandering...",
  "Metamorphosing...",
  "Misting...",
  "Moonwalking...",
  "Moseying...",
  "Mulling...",
  "Mustering...",
  "Musing...",
  "Nebulizing...",
  "Nesting...",
  "Newspapering...",
  "Noodling...",
  "Nucleating...",
  "Orbiting...",
  "Orchestrating...",
  "Osmosing...",
  "Perambulating...",
  "Percolating...",
  "Perusing...",
  "Philosophising...",
  "Photosynthesizing...",
  "Pollinating...",
  "Pondering...",
  "Pontificating...",
  "Pouncing...",
  "Precipitating...",
  "Prestidigitating...",
  "Processing...",
  "Proofing...",
  "Propagating...",
  "Puttering...",
  "Puzzling...",
  "Quantumizing...",
  "Razzle-dazzling...",
  "Razzmatazzing...",
  "Recombobulating...",
  "Reticulating...",
  "Roosting...",
  "Ruminating...",
  "Sautéing...",
  "Scampering...",
  "Schlepping...",
  "Scurrying...",
  "Seasoning...",
  "Shenaniganing...",
  "Shimmying...",
  "Simmering...",
  "Skedaddling...",
  "Sketching...",
  "Slithering...",
  "Smooshing...",
  "Sock-hopping...",
  "Spelunking...",
  "Spinning...",
  "Sprouting...",
  "Stewing...",
  "Sublimating...",
  "Swirling...",
  "Swooping...",
  "Symbioting...",
  "Synthesizing...",
  "Tempering...",
  "Thinking...",
  "Thundering...",
  "Tinkering...",
  "Tomfoolering...",
  "Topsy-turvying...",
  "Transfiguring...",
  "Transmuting...",
  "Twisting...",
  "Undulating...",
  "Unfurling...",
  "Unravelling...",
  "Vibing...",
  "Waddling...",
  "Wandering...",
  "Warping...",
  "Whatchamacalliting...",
  "Whirlpooling...",
  "Whirring...",
  "Whisking...",
  "Wibbling...",
  "Working...",
  "Wrangling...",
  "Zesting...",
  "Zigzagging...",

  // Long
  "Consulting the void...",
  "Asking the electrons...",
  "Bribing the compiler...",
  "Negotiating with entropy...",
  "Whispering to the bits...",
  "Tickling the stack...",
  "Massaging the heap...",
  "Appeasing the garbage collector...",
  "Summoning semicolons...",
  "Herding pointers...",
  "Untangling spaghetti...",
  "Polishing the algorithms...",
  "Waxing philosophical...",
  "Consulting ancient scrolls...",
  "Reading tea leaves...",
  "Shaking the magic 8-ball...",
  "Sacrificing to the demo gods...",
  "Warming up the hamsters...",
  "Spinning up the squirrels...",
  "Caffeinating...",
  "Existentially questioning...",
  "Having a little think...",
  "Stroking chin thoughtfully...",
  "Squinting at the problem...",
  "Staring into the abyss...",
  "Abyss staring back...",
  "Achieving enlightenment...",
  "Transcending mere computation...",
  "Ascending to a higher plane...",
  "Communing with the machine spirit...",
  "Performing arcane rituals...",
  "Invoking elder functions...",
  "Consulting the oracle...",
  "Divining the answer...",
  "Scrying the codebase...",
  "Dowsing for bugs...",
  "Rearranging deck chairs...",
  "Shuffling bits around...",
  "Aligning the chakras...",
  "Reticulating splines...",
  "Reversing the polarity...",
  "Calibrating the flux capacitor...",
  "Charging the crystals...",
  "Tuning the vibrations...",
  "Adjusting the cosmic frequency...",
  "Waiting for a sign...",
  "Hoping for the best...",
  "Manifesting solutions...",
  "Willing it into existence...",
  "Believing really hard...",
  "Politely asking the CPU...",
  "Bribing the runtime...",
  "Flirting with the database...",
  "Sweet-talking the API...",
  "Negotiating with deadlines...",
  "Having words with the cache...",
  "Reasoning with the memory...",
  "Pleading with the logs...",
  "Bargaining with fate...",
  "Making offerings to the CI...",
  "Praying to the uptime gods...",
  "Consulting the rubber duck...",
  "Interrogating the stack trace...",
  "Cross-examining the debugger...",
  "Petitioning the kernel...",
  "Lobbying the scheduler...",
  "Schmoozing the network...",
  "Buttering up the firewall...",
  "Wining and dining the servers...",
  "Taking the bytes out for lunch...",
  "Giving the code a pep talk...",
  "Reading the room...",
  "Checking under the hood...",
  "Kicking the tires...",
  "Shaking loose the cobwebs...",
  "Dusting off the neurons...",
  "Greasing the gears...",
  "Oiling the cogs...",
  "Winding up the clockwork...",
  "Stoking the furnace...",
  "Feeding the machine...",
  "Watering the logic tree...",
  "Pruning the decision branches...",
  "Harvesting the outputs...",
  "Planting computational seeds...",
  "Nurturing the algorithm...",
  "Raising the exceptions...",
  "Taming wild pointers...",
  "Herding cats in memory...",
  "Teaching old code new tricks...",
  "Whispering sweet nothings to the compiler...",
  "Serenading the syntax...",
  "Dancing with dependencies...",
  "Waltzing through the codebase...",
  "Tangoing with type errors...",
  "Doing the deployment dance...",
  "Having a moment of clarity...",
  "Experiencing a flash of insight...",
  "Channeling the ancient developers...",
  "Receiving transmissions from the cloud...",
  "Asking the hamsters to run faster...",
  "Convincing the pixels to cooperate...",
  "Teaching electrons new tricks...",
  "Bribing the byte fairies...",
  "Whispering passwords to the void...",
  "Negotiating with cosmic rays...",
  "Flattering the floating points...",
  "Seducing the semicolons...",
  "Wooing the while loops...",
  "Charming the curly braces...",
  "Hypnotizing the hash tables...",
  "Mesmerizing the memory banks...",
  "Enchanting the error handlers...",
  "Bewitching the boolean logic...",
  "Spellbinding the stack frames...",
  "Hexing the hexadecimals...",
  "Jinxing the JSON parsers...",
  "Cursing the cache misses...",
  "Blessing the build process...",
  "Anointing the algorithms...",
  "Consecrating the callbacks...",
  "Sanctifying the source code...",
  "Exorcising the exceptions...",
  "Purifying the parameters...",
  "Cleansing the closures...",
  "Baptizing the binary...",
  "Absolving the abstractions...",
  "Redeeming the recursion...",
  "Forgiving the for loops...",
  "Pardoning the pointers...",
  "Liberating the lambdas...",
  "Emancipating the enums...",
  "Freeing the functions...",
  "Releasing the references...",
  "Unbinding the variables...",
  "Untying the type knots...",
  "Unraveling the regex...",
  "Decoding the mysteries...",
  "Cracking the conundrums...",
  "Solving the riddles of RAM...",
  "Unlocking the secrets of silicon...",
  "Discovering hidden semicolons...",
  "Unearthing buried bugs...",
  "Excavating ancient APIs...",
  "Archeologically analyzing the architecture...",
  "Fossil hunting in the functions...",
  "Spelunking through the stack...",
  "Scuba diving in the data...",
  "Snorkeling through the streams...",
  "Parasailing past the parameters...",
  "Hang gliding through the heap...",
  "Bungee jumping into the backend...",
  "Skydiving through the source...",
  "Surfing the syntax waves...",
  "Skateboarding down the stack trace...",
  "Snowboarding through the schemas...",
  "Mountain climbing the modules...",
  "Hiking through the headers...",
  "Trekking through the trees...",
  "Backpacking through the binaries...",
  "Camping in the codebase...",
  "Glamping in the globals...",
  "Picnicking with the processes...",
  "Barbecuing the bugs...",
  "Roasting the race conditions...",
  "Grilling the glitches...",
  "Sautéing the syntax errors...",
  "Flambéing the failures...",
  "Caramelizing the callbacks...",
  "Braising the breakpoints...",
  "Poaching the pointers...",
  "Blanching the branches...",
  "Searing the segments...",
  "Smoking the subroutines...",
  "Curing the code smells...",
  "Pickling the packages...",
  "Preserving the protocols...",
  "Canning the constants...",
  "Bottling the buffers...",
  "Jarring the JavaScript...",
  "Decanting the data structures...",
  "Aerating the arrays...",
  "Letting the logic breathe...",
  "Aging the algorithms gracefully...",
  "Maturing the methods...",
  "Ripening the results...",
  "Seasoning the solutions...",
  "Spicing up the specs...",
  "Garnishing the getters...",
  "Plating the output nicely...",
  "Presenting with pizzazz...",
  "Adding a dash of elegance...",
  "Sprinkling some magic dust...",
  "Drizzling debug sauce...",
  "Folding in the features...",
  "Whisking the widgets...",
  "Kneading the namespaces...",
  "Rolling out the runtime...",
  "Proofing the promises...",
  "Letting the dough rise...",
  "Baking at 350 kilobytes...",
  "Frosting the functions...",
  "Decorating the deployment...",
  "Icing the interfaces...",
  "Glazing the graphics...",
  "Topping with tests...",
  "Cherry-picking the commits...",
];

function pickRandom(): string {
  return messages[Math.floor(Math.random() * messages.length)];
}

function ansiRgb(r: number, g: number, b: number, text: string): string {
  return `\x1b[38;2;${r};${g};${b}m${text}\x1b[39m`;
}

function hsvToRgb(h: number, s: number, v: number): [number, number, number] {
  const c = v * s;
  const hh = h / 60;
  const x = c * (1 - Math.abs((hh % 2) - 1));
  let r = 0;
  let g = 0;
  let b = 0;

  if (hh >= 0 && hh < 1) [r, g, b] = [c, x, 0];
  else if (hh < 2) [r, g, b] = [x, c, 0];
  else if (hh < 3) [r, g, b] = [0, c, x];
  else if (hh < 4) [r, g, b] = [0, x, c];
  else if (hh < 5) [r, g, b] = [x, 0, c];
  else [r, g, b] = [c, 0, x];

  const m = v - c;
  return [
    Math.round((r + m) * 255),
    Math.round((g + m) * 255),
    Math.round((b + m) * 255),
  ];
}

function normalShimmer(text: string, _theme: { fg(color: string, text: string): string }, tick: number): string {
  const chars = [...text];
  const width = 5;
  const center = tick % (chars.length + width * 2) - width;

  return chars
    .map((char, i) => {
      const distance = Math.abs(i - center);
      if (distance < 0.7) return ansiRgb(245, 247, 255, char);
      if (distance < 1.6) return ansiRgb(200, 225, 255, char);
      if (distance < 2.6) return ansiRgb(150, 170, 215, char);
      return ansiRgb(115, 125, 155, char);
    })
    .join("");
}

function rainbowShimmer(text: string, _theme: { fg(color: string, text: string): string }, tick: number): string {
  const chars = [...text];
  return chars
    .map((char, i) => {
      if (char === " ") return char;
      const hue = (tick * 14 + i * 18) % 360;
      const [r, g, b] = hsvToRgb(hue, 0.7, 1);
      return ansiRgb(r, g, b, char);
    })
    .join("");
}

export default function (pi: ExtensionAPI) {
  let timer: ReturnType<typeof setInterval> | undefined;
  let turnCount = 0;

  function stop(ctx: { ui: { setWorkingMessage(message?: string): void } }): void {
    if (timer) clearInterval(timer);
    timer = undefined;
    ctx.ui.setWorkingMessage();
  }

  pi.on("turn_start", async (_event, ctx) => {
    if (timer) clearInterval(timer);

    const message = pickRandom();
    turnCount += 1;
    const useRainbow = turnCount % 8 === 0;
    let tick = 0;
    const renderMessage = useRainbow
      ? () => rainbowShimmer(message, ctx.ui.theme, tick++)
      : () => normalShimmer(message, ctx.ui.theme, tick++);
    const render = () => ctx.ui.setWorkingMessage(renderMessage());

    render();
    timer = setInterval(render, useRainbow ? 90 : 80);
  });

  pi.on("turn_end", async (_event, ctx) => {
    stop(ctx);
  });
}
